export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT = "LOGOUT";


export const GET_PROVIDER_DATA = 'GET_PROVIDER_DATA';
export const PROVIDER_DATA_RECEIVED = 'PROVIDER_DATA_RECEIVED';
export const CREATE_PROVIDER = 'CREATE_PROVIDER';
export const UPDATE_PROVIDER = 'UPDATE_PROVIDER';
export const PROVIDER_EDIT_RECEIVED ='PROVIDER_EDIT_RECEIVED';
export const PROVIDER_HISTORY_RECEIVED = "PROVIDER_HISTORY_RECEIVED";
export const CLEAR_PROVIDER = "CLEAR_PROVIDER";
export const CLEAR_DATA= "CLEAR_DATA";


export const GET_CHANNELS = 'GET_CHANNELS';
export const CHANNELS_RECEIVED = 'CHANNELS_RECEIVED';
export const SELECT_CHANNEL = 'SELECT_CHANNEL';


export const GET_CHAINCODES_FOR_CHANNEL = 'GET_CHAINCODES_FOR_CHANNEL';
export const CHAINCODES_FOR_CHANNEL_RECEIVED = 'CHAINCODES_FOR_CHANNEL_RECEIVED';
export const SELECT_CHAINCODE = 'SELECT_CHAINCODE';


export const GET_CONFIG = 'GET_CONFIG';
export const PEERS_RECEIVED = 'PEERS_RECEIVED';
export const ORG_RECEIVED = 'ORG_RECEIVED';
export const SELECT_PEER = 'SELECT_PEER';

export const REQUEST_MADE = 'REQUEST_MADE';
export const REQUEST_RETURNED = 'REQUEST_RETURNED';


export const TX_HISTORY_RECEIVED = 'TX_HISTORY_RECEIVED';

